/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DmScanlib */

#ifndef _Included_DmScanlib
#define _Included_DmScanlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DmScanlib
 * Method:    getScanlibDataTest
 * Signature: (ILjava/lang/String;LScanSettings;LScanCoordinates;LDecodeProfile;LDecodeSettings;)LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_getScanlibDataTest
  (JNIEnv *, jclass, jint, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     DmScanlib
 * Method:    slIsTwainAvailable
 * Signature: ()LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slIsTwainAvailable
  (JNIEnv *, jclass);

/*
 * Class:     DmScanlib
 * Method:    slSelectSourceAsDefault
 * Signature: ()LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slSelectSourceAsDefault
  (JNIEnv *, jclass);

/*
 * Class:     DmScanlib
 * Method:    slGetScannerCapability
 * Signature: ()LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slGetScannerCapability
  (JNIEnv *, jclass);

/*
 * Class:     DmScanlib
 * Method:    slScanImage
 * Signature: (ILjava/lang/String;LScanSettings;LScanCoordinates;)LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slScanImage
  (JNIEnv *, jclass, jint, jstring, jobject, jobject);

/*
 * Class:     DmScanlib
 * Method:    slScanFlatbed
 * Signature: (ILjava/lang/String;LScanSettings;)LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slScanFlatbed
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     DmScanlib
 * Method:    slDecodePlate
 * Signature: (ILScanSettings;LScanCoordinates;LDecodeProfile;LDecodeSettings;)LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slDecodePlate
  (JNIEnv *, jclass, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     DmScanlib
 * Method:    slDecodeImage
 * Signature: (ILjava/lang/String;LDecodeProfile;LDecodeSettings;)LScanlibData;
 */
JNIEXPORT jobject JNICALL Java_DmScanlib_slDecodeImage
  (JNIEnv *, jclass, jint, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
