/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ualberta_med_scannerconfig_dmscanlib_ScanLib */

#ifndef _Included_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
#define _Included_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MIN_PLATE_NUM
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MIN_PLATE_NUM 1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MAX_PLATE_NUM
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MAX_PLATE_NUM 5L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_SUCCESS
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_SUCCESS 0L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_FAIL
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_FAIL -1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_TWAIN_UNAVAIL
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_TWAIN_UNAVAIL -2L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_DPI
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_DPI -3L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_NOTHING_DECODED
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_NOTHING_DECODED -4L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_IMAGE
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_IMAGE -5L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_NOTHING_TO_DECODE
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INVALID_NOTHING_TO_DECODE -6L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INCORRECT_DPI_SCANNED
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_INCORRECT_DPI_SCANNED -7L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_WIA
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_WIA 1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_300
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_300 2L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_400
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_400 4L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_600
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_600 8L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_SCANNER
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_SCANNER 16L
/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    selectSourceAsDefault
 * Signature: ()Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_selectSourceAsDefault
  (JNIEnv *, jobject);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    getScannerCapability
 * Signature: ()Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_getScannerCapability
  (JNIEnv *, jobject);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    scanImage
 * Signature: (JJIIDDDDLjava/lang/String;)Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_scanImage
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    scanFlatbed
 * Signature: (JJIILjava/lang/String;)Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_scanFlatbed
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jstring);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    scanAndDecode
 * Signature: (JJIIDDDDLedu/ualberta/med/scannerconfig/dmscanlib/DecodeOptions;[Ledu/ualberta/med/scannerconfig/dmscanlib/CellRectangle;)Ledu/ualberta/med/scannerconfig/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_scanAndDecode
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jobject, jobjectArray);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    decodeImage
 * Signature: (JLjava/lang/String;Ledu/ualberta/med/scannerconfig/dmscanlib/DecodeOptions;[Ledu/ualberta/med/scannerconfig/dmscanlib/CellRectangle;)Ledu/ualberta/med/scannerconfig/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_decodeImage
  (JNIEnv *, jobject, jlong, jstring, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
