/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ualberta_med_scannerconfig_dmscanlib_ScanLib */

#ifndef _Included_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
#define _Included_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MIN_PLATE_NUM
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MIN_PLATE_NUM 1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MAX_PLATE_NUM
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_MAX_PLATE_NUM 5L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_SUCCESS
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_SUCCESS 0L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_FAIL
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_SC_FAIL -1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_WIA
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_WIA 1L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_300
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_300 2L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_400
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_400 4L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_600
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_DPI_600 8L
#undef edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_SCANNER
#define edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_CAP_IS_SCANNER 16L
/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    isTwainAvailable
 * Signature: ()Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_isTwainAvailable
  (JNIEnv *, jobject);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    selectSourceAsDefault
 * Signature: ()Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_selectSourceAsDefault
  (JNIEnv *, jobject);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    getScannerCapability
 * Signature: ()Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_getScannerCapability
  (JNIEnv *, jobject);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    scanImage
 * Signature: (JJIILedu/ualberta/med/scannerconfig/dmscanlib/ScanRegion;Ljava/lang/String;)Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_scanImage
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jobject, jstring);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    scanFlatbed
 * Signature: (JJIILjava/lang/String;)Ledu/ualberta/med/scannerconfig/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_scanFlatbed
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jstring);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    decodePlate
 * Signature: (JJIIJLedu/ualberta/med/scannerconfig/dmscanlib/ScanRegion;DJJJDDDJJJJ)Ledu/ualberta/med/scannerconfig/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_decodePlate
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jobject, jdouble, jlong, jlong, jlong, jdouble, jdouble, jdouble, jlong, jlong, jlong, jlong);

/*
 * Class:     edu_ualberta_med_scannerconfig_dmscanlib_ScanLib
 * Method:    decodeImage
 * Signature: (JJLjava/lang/String;DJJJDDDJJJJ)Ledu/ualberta/med/scannerconfig/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_edu_ualberta_med_scannerconfig_dmscanlib_ScanLib_decodeImage
  (JNIEnv *, jobject, jlong, jlong, jstring, jdouble, jlong, jlong, jlong, jdouble, jdouble, jdouble, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
