/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Thu Jun 25 16:44:47 MDT 2009 ----! */

#include <jni.h>
#include <stdlib.h>

#include <assert.h>

 #include "ScanLib.h"

/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slCalibrateToPlate(int dpi, int plateNum)
 *     C function: int slCalibrateToPlate(unsigned int dpi, unsigned int plateNum);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slCalibrateToPlate__II(JNIEnv *env, jclass _unused, jint dpi, jint plateNum) {
  int _res;
  _res = slCalibrateToPlate((int) dpi, (int) plateNum);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slConfigPlateFrame(int plateNum, double left, double top, double right, double bottom)
 *     C function: int slConfigPlateFrame(unsigned int plateNum, double left, double top, double right, double bottom);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slConfigPlateFrame__IDDDD(JNIEnv *env, jclass _unused, jint plateNum, jdouble left, jdouble top, jdouble right, jdouble bottom) {
  int _res;
  _res = slConfigPlateFrame((int) plateNum, (double) left, (double) top, (double) right, (double) bottom);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slConfigScannerBrightness(int brightness)
 *     C function: int slConfigScannerBrightness(int brightness);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slConfigScannerBrightness__I(JNIEnv *env, jclass _unused, jint brightness) {
  int _res;
  _res = slConfigScannerBrightness((int) brightness);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slConfigScannerContrast(int contrast)
 *     C function: int slConfigScannerContrast(int contrast);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slConfigScannerContrast__I(JNIEnv *env, jclass _unused, jint contrast) {
  int _res;
  _res = slConfigScannerContrast((int) contrast);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slDecodeImage(int plateNum, java.nio.ByteBuffer filename)
 *     C function: int slDecodeImage(unsigned int plateNum, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slDecodeImage0__ILjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint plateNum, jobject filename, jint filename_byte_offset) {
  char * _ptr1 = NULL;
  int _res;
    if (filename != NULL) {
        _ptr1 = (char *) (((char*) (*env)->GetDirectBufferAddress(env, filename)) + filename_byte_offset);
    }
  _res = slDecodeImage((int) plateNum, (char *) _ptr1);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slDecodeImage(int plateNum, java.nio.ByteBuffer filename)
 *     C function: int slDecodeImage(unsigned int plateNum, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slDecodeImage1__ILjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint plateNum, jobject filename, jint filename_byte_offset) {
  char * _ptr1 = NULL;
  int _res;
  if (filename != NULL) {
    _ptr1 = (char *) (((char*) (*env)->GetPrimitiveArrayCritical(env, filename, NULL)) + filename_byte_offset);
  }
  _res = slDecodeImage((int) plateNum, (char *) _ptr1);
  if (filename != NULL) {
    (*env)->ReleasePrimitiveArrayCritical(env, filename, _ptr1, 0);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slDecodePlate(int dpi, int plateNum)
 *     C function: int slDecodePlate(unsigned int dpi, unsigned int plateNum);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slDecodePlate__II(JNIEnv *env, jclass _unused, jint dpi, jint plateNum) {
  int _res;
  _res = slDecodePlate((int) dpi, (int) plateNum);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slIsTwainAvailable()
 *     C function: int slIsTwainAvailable();
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slIsTwainAvailable__(JNIEnv *env, jclass _unused) {
  int _res;
  _res = slIsTwainAvailable();
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slScanImage(int dpi, double left, double top, double right, double bottom, java.nio.ByteBuffer filename)
 *     C function: int slScanImage(unsigned int dpi, double left, double top, double right, double bottom, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slScanImage0__IDDDDLjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint dpi, jdouble left, jdouble top, jdouble right, jdouble bottom, jobject filename, jint filename_byte_offset) {
  char * _ptr5 = NULL;
  int _res;
    if (filename != NULL) {
        _ptr5 = (char *) (((char*) (*env)->GetDirectBufferAddress(env, filename)) + filename_byte_offset);
    }
  _res = slScanImage((int) dpi, (double) left, (double) top, (double) right, (double) bottom, (char *) _ptr5);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slScanImage(int dpi, double left, double top, double right, double bottom, java.nio.ByteBuffer filename)
 *     C function: int slScanImage(unsigned int dpi, double left, double top, double right, double bottom, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slScanImage1__IDDDDLjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint dpi, jdouble left, jdouble top, jdouble right, jdouble bottom, jobject filename, jint filename_byte_offset) {
  char * _ptr5 = NULL;
  int _res;
  if (filename != NULL) {
    _ptr5 = (char *) (((char*) (*env)->GetPrimitiveArrayCritical(env, filename, NULL)) + filename_byte_offset);
  }
  _res = slScanImage((int) dpi, (double) left, (double) top, (double) right, (double) bottom, (char *) _ptr5);
  if (filename != NULL) {
    (*env)->ReleasePrimitiveArrayCritical(env, filename, _ptr5, 0);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slScanPlate(int dpi, int plateNum, java.nio.ByteBuffer filename)
 *     C function: int slScanPlate(unsigned int dpi, unsigned int plateNum, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slScanPlate0__IILjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint dpi, jint plateNum, jobject filename, jint filename_byte_offset) {
  char * _ptr2 = NULL;
  int _res;
    if (filename != NULL) {
        _ptr2 = (char *) (((char*) (*env)->GetDirectBufferAddress(env, filename)) + filename_byte_offset);
    }
  _res = slScanPlate((int) dpi, (int) plateNum, (char *) _ptr2);
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slScanPlate(int dpi, int plateNum, java.nio.ByteBuffer filename)
 *     C function: int slScanPlate(unsigned int dpi, unsigned int plateNum, char *  filename);
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slScanPlate1__IILjava_lang_Object_2I(JNIEnv *env, jclass _unused, jint dpi, jint plateNum, jobject filename, jint filename_byte_offset) {
  char * _ptr2 = NULL;
  int _res;
  if (filename != NULL) {
    _ptr2 = (char *) (((char*) (*env)->GetPrimitiveArrayCritical(env, filename, NULL)) + filename_byte_offset);
  }
  _res = slScanPlate((int) dpi, (int) plateNum, (char *) _ptr2);
  if (filename != NULL) {
    (*env)->ReleasePrimitiveArrayCritical(env, filename, _ptr2, 0);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: edu.ualberta.med.biobank.scanlib.ScanLib
 *    Java method: int slSelectSourceAsDefault()
 *     C function: int slSelectSourceAsDefault();
 */
JNIEXPORT jint JNICALL 
Java_edu_ualberta_med_biobank_scanlib_ScanLib_slSelectSourceAsDefault__(JNIEnv *env, jclass _unused) {
  int _res;
  _res = slSelectSourceAsDefault();
  return _res;
}


